theme: jekyll-theme-minimal

# Title of your blog; shows in the header
title: "Patrick Granahan"

author: "Patrick Granahan"

# Description of your content (will only be used on Google Search)
description: "Patrick Granahan's website and blog"

# "true" or "false" to indicate whether to provide a download URL
show_downloads: false

# Your Google Analytics tracking ID
google_analytics: UA-50072911-1

# Enables automatic sitemap generation (https://help.github.com/articles/sitemaps-for-github-pages/)
gems:
  - jekyll-sitemap

# social media account handles
github: pjgranahan
linkedin: pjgranahan

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "Undergraduate at Rice University pursuing a Bachelor of Science in Computer Science."

url: "http://www.pjgranahan.com"