version: 0.1
   
phases:
  install:
    commands:
      # Install nodejs (https://nodejs.org/en/download/package-manager/) (needed by jekyll)
      - curl -sL https://deb.nodesource.com/setup_7.x | bash -
      - apt-get install -y nodejs
      # Install bundler and bundle install (https://github.com/github/pages-gem#usage)
      - gem install bundler
      # Speeds up nokogiri install by disabling redundant work (http://awesomism.co.uk/nokogiri-slow-install/)
      - env NOKOGIRI_USE_SYSTEM_LIBRARIES=true bundle install
  build:
    commands:
      - bundle exec jekyll build
      - aws s3 sync _site/ "s3://${BUCKET_NAME}" --delete
