# hostname (and path) to the root, e.g. http://spf13.com/
baseURL = "https://www.pjgranahan.com"

# google analytics tracking id
googleAnalytics = "UA-50072911-1"

title = "Patrick Granahan"

enableGitInfo = true

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodeFencesGuessSyntax = true

[permalinks]
  post = "/:filename/"

[params]
  # social media account handles
  Github = "pjgranahan"
  Linkedin = "pjgranahan"

  AuthorBio = "Senior at Rice University. Bachelor of Science in Computer Science."

  GithubRepoUrl = "https://github.com/pjgranahan/pjgranahan.com"

  GoogleInvisibleRecaptchaSiteKey = "6LcrUSAUAAAAAIiMzkDMrSiXT4OHE5tAXnVo8W4P"