# hostname (and path) to the root, e.g. http://spf13.com/
baseURL = "https://www.pjgranahan.com"

# google analytics tracking id
googleAnalytics = "UA-50072911-1"

title = "Patrick Granahan"

enableGitInfo = true

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodeFencesGuessSyntax = true

[permalinks]
  post = "/:filename/"

[params]
  # social media account handles
  Github = "pjgranahan"
  Linkedin = "pjgranahan"

  AuthorBio = "Rice University Alumnus."
  Disclaimer = "Opinions are my own and not necessarily the views of my employer."
  
  GithubRepoUrl = "https://github.com/pjgranahan/pjgranahan.com"

  RecaptchaSiteKey = "6LeRgiAUAAAAADyHra3UqyHvPvoXTWRItTz8a3Hj"
